OnlineShoppingStore.UI/Models/CartIndexViewModel.cs
using OnlineShoppingStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineShoppingStore.UI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

OnlineShoppingStore.UI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineShoppingStore.UI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages {

            get
            {
                return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage);
            }
        }

    }
}

OnlineShoppingStore.UI/Models/ProductListViewModel.cs
using OnlineShoppingStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineShoppingStore.UI.Models
{
    public class ProductListViewModel
    {
        public IEnumerable<Product> Products { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }

    }
}

OnlineShoppingStore.UI/Controllers/CartController.cs
using OnlineShoppingStore.Domain.Abstract;
using OnlineShoppingStore.Domain.Entities;
using OnlineShoppingStore.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShoppingStore.UI.Controllers
{
    public class CartController : Controller
    {
       private IProductRepository repository;

       public CartController(IProductRepository repo)
       {
           repository = repo;
       }

        public ViewResult Index(Cart cart, string returnUrl)
       {
           return View(
               new CartIndexViewModel {Cart = cart, ReturnUrl = returnUrl }
               );
       }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
       {
           Product product = repository.Products.FirstOrDefault(p => p.ProductId == productId);

            if(product != null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
       }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

       
    }
}

OnlineShoppingStore.UI/Controllers/NavController.cs
using OnlineShoppingStore.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShoppingStore.UI.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository repository;

        public NavController(IProductRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return PartialView(categories);
        }
    }
}

OnlineShoppingStore.UI/Controllers/ProductController.cs
using OnlineShoppingStore.Domain.Abstract;
using OnlineShoppingStore.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShoppingStore.UI.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepository repository;
        public int pageSize = 3;
        public ProductController(IProductRepository repo)
        {
            repository = repo;

        }

        public ViewResult List(string category, int page = 1)
        {

            ProductListViewModel model = new ProductListViewModel
            {
                Products = repository.Products
                            .Where(p => category == null || p.Category == category)
                            .OrderBy(p => p.ProductId)
                            .Skip((page - 1) * pageSize)
                            .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ? 
                                repository.Products.Count() : 
                                repository.Products.Where(a => a.Category == category).Count()
                },
                CurrentCategory = category
            };

            return View(model);
        }
    }
}

OnlineShoppingStore.UI/Views/Cart/Checkout.cshtml
@model OnlineShoppingStore.Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "Online Shopping Store : Checkout";
}

<h2>Check out now</h2>

<p>Please enter the details</p>

@using (Html.BeginForm())
{
    <h3>Ship to</h3>
    <div class="form-group">
        <label>Name:</label>
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Street:</label>
        @Html.TextBoxFor(x => x.Street, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>City:</label>
        @Html.TextBoxFor(x => x.City, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>PostCode:</label>
        @Html.TextBoxFor(x => x.PostCode, new { @class = "form-control" })
    </div>
    <div class="checkbox">
        <label>@Html.EditorFor(x => x.GiftWrap)
        Gift wrap these items</label>        
    </div>
    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="Complete order" />
    </div>
}

OnlineShoppingStore.UI/Views/Cart/Index.cshtml
@model OnlineShoppingStore.UI.Models.CartIndexViewModel
<style>
    #cartTable td{vertical-align: middle;}
</style>

@{
    ViewBag.Title = "Sports Store : Your Cart";
}

<h2>Your Cart</h2>
<table id="cartTable" class="table">
    <thead>
        <tr>
            <th> Quantity</th>
            <th> Item</th>
            <th class="text-right"> Price</th>
            <th class="text-right">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach( var line in Model.Cart.Lines)
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Product.Name</td>
                <td class="text-right">
                    @line.Product.Price.ToString("c")
                </td>
                <td class="text-right">
                    @((line.Quantity * line.Product.Price).ToString("c"))
                </td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    {
                        @Html.Hidden("ProductId", line.Product.ProductId)
                        @Html.HiddenFor(x => x.ReturnUrl)
                        <input class="btn btn-sm btn-warning" type="submit" value="Remove" />
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">
                Total:
            </td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("c")
            </td>
        </tr>
    </tfoot>
</table>
<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">
        Continue Shopping
    </a>
    @Html.ActionLink("Checkout now", "Checkout", null, new { @class ="btn btn-primary"})
</div>

OnlineShoppingStore.UI/Views/Cart/Summary.cshtml
@model OnlineShoppingStore.Domain.Entities.Cart

<div class="navbar-right">
    @Html.ActionLink("Checkout", "Index", "Cart",
    new { returnUrl = Request.Url.PathAndQuery },
    new { @class= "btn btn-default navbar-btn"})
</div>

<div class="navbar-text navbar-right">
    <b>Your Cart:</b>
    @Model.Lines.Sum(x => x.Quantity) item(s), 
    @Model.ComputeTotalValue().ToString("c")
</div>

OnlineShoppingStore.UI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Home", "List", "Product", null, new { @class= "btn btn-block btn-default btn-lg" })


@foreach(var link in Model)
{
    @Html.RouteLink(link, new
        {
            controller = "Product",
            action = "List",
            category = link,
            page = 1

       }, new { @class = "btn btn-block btn-default btn-lg" + (link == ViewBag.SelectedCategory?  " btn-primary" : "")})
}

OnlineShoppingStore.UI/Views/Product/List.cshtml
@model OnlineShoppingStore.UI.Models.ProductListViewModel

@{
    ViewBag.Title = "Products";
}
   

@foreach (var item in Model.Products)
{
    @Html.Partial("ProductSummary", item)
}
    
<div class="btn-group pull-right">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new  { page = x, category = Model.CurrentCategory }))
</div>

OnlineShoppingStore.UI/Views/Shared/ProductSummary.cshtml
@model OnlineShoppingStore.Domain.Entities.Product


<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("c")</span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.ProductId)
            @Html.Hidden("returnUrl",Request.Url.PathAndQuery)
            <input type="submit" class="btn  btn-success" value="Add to cart" />
        </div>
    }
    <span class="lead">@Model.Description</span>
</div>

OnlineShoppingStore.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Online Shopping Store</title>   
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
</head>
<body>    
      <div class="navbar navbar-inverse" role="navigation">
          <a class="navbar-brand" href="#">Online Shpping Store</a>
          @Html.Action("Summary", "Cart")
      </div>
    <div class="row panel">
        <div id="categories" class="col-lg-3">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-lg-7">
            @RenderBody()
        </div>
    </div>
      
</body>
</html>